version: '3.8'

services:
  # SQL Server Database
  speedreading-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gaplatform-speedreading-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_SA_PASSWORD:-GAPlatform123!}"
      MSSQL_PID: "Developer"
    ports:
      - "${DB_PORT:-1438}:1433"
    volumes:
      - speedreading_db_data:/var/opt/mssql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - gaplatform-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${DB_SA_PASSWORD:-GAPlatform123!}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  # Redis Cache
  speedreading-redis:
    image: redis:7-alpine
    container_name: gaplatform-speedreading-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - speedreading_redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - gaplatform-network
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Speed Reading API Service
  speedreading-api:
    build:
      context: .
      dockerfile: SpeedReading.API/Dockerfile
    container_name: gaplatform-speedreading-api
    environment:
      # ASP.NET Core Configuration
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:-Development}"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_HTTP_PORTS: "80"
      
      # Database Configuration
      ConnectionStrings__DefaultConnection: "Server=speedreading-db,1433;Database=GAPlatform.SpeedReading;User Id=sa;Password=${DB_SA_PASSWORD:-GAPlatform123!};TrustServerCertificate=true;MultipleActiveResultSets=true;"
      
      # Redis Configuration
      ConnectionStrings__Redis: "speedreading-redis:6379"
      
      # Identity Server Configuration
      IdentityServer__Authority: "${IDENTITY_SERVER_URL:-http://identity-api:80}"
      IdentityServer__Audience: "gaeducation.api"
      
      # Logging Configuration
      Serilog__MinimumLevel: "${LOG_LEVEL:-Information}"
      Serilog__WriteTo__0__Name: "Console"
      Serilog__WriteTo__1__Name: "File"
      Serilog__WriteTo__1__Args__path: "logs/speedreading-.txt"
      Serilog__WriteTo__1__Args__rollingInterval: "Day"
      
      # Security Configuration
      AllowedOrigins__0: "${FRONTEND_URL:-http://localhost:4200}"
      AllowedOrigins__1: "${ADMIN_URL:-http://localhost:7001}"
      
      # Service Configuration
      SERVICE_NAME: "SpeedReading.API"
      SERVICE_VERSION: "1.0.0"
      ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:-Development}"
      
      # External Services
      IDENTITY_SERVER_URL: "${IDENTITY_SERVER_URL:-http://identity-api:80}"
      
      # Speed Reading Specific Configuration
      SpeedReading__MaxWordsPerMinute: "${MAX_WPM:-1000}"
      SpeedReading__DefaultWordsPerMinute: "${DEFAULT_WPM:-200}"
      SpeedReading__CacheExpirationMinutes: "${CACHE_EXPIRATION:-60}"
      SpeedReading__MaxTextLength: "${MAX_TEXT_LENGTH:-50000}"
    ports:
      - "${API_PORT:-5000}:80"
    depends_on:
      speedreading-db:
        condition: service_healthy
      speedreading-redis:
        condition: service_healthy
    volumes:
      - speedreading_logs:/app/logs
      - ./appsettings.json:/app/appsettings.json:ro
      - ./appsettings.${ASPNETCORE_ENVIRONMENT:-Development}.json:/app/appsettings.${ASPNETCORE_ENVIRONMENT:-Development}.json:ro
    networks:
      - gaplatform-network
    healthcheck:
      test: curl -f http://localhost:80/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Networks
networks:
  gaplatform-network:
    name: gaplatform-network
    driver: bridge
    external: true

# Volumes
volumes:
  speedreading_db_data:
    name: gaplatform-speedreading-db-data
    driver: local
  speedreading_redis_data:
    name: gaplatform-speedreading-redis-data
    driver: local
  speedreading_logs:
    name: gaplatform-speedreading-logs
    driver: local